// Generated by CoffeeScript 1.6.3
(function() {
  var cache_retrieve, cache_store, data, events, memoize;

  events = require("events");

  data = {};

  cache_store = function(callback, key, value) {
    if (callback) {
      callback(null, value);
    }
    return data[key] = value;
  };

  cache_retrieve = function(callback, key) {
    if (key === "2") {
      return setTimeout(callback, 3000, null, data[key]);
    } else {
      return callback(null, data[key]);
    }
  };

  memoize = function(slow_fn) {
    var slice;
    if (typeof slow_fn === "function") {
      slice = Array.prototype.slice;
      return function() {
        var args, eventEmitter, input, sendCallback, slow_fn_callback;
        args = slice.call(arguments);
        slow_fn_callback = args[0];
        input = args[1];
        eventEmitter = new events.EventEmitter();
        sendCallback = sendCallback = function(err, value, where_it_comes_from) {
          console.log("From " + where_it_comes_from);
          return slow_fn_callback(err, value);
        };
        eventEmitter.on("completed", sendCallback);
        process.nextTick(function() {
          return cache_retrieve((function(err, value) {
            if (value) {
              console.log("Llegue cache");
              eventEmitter.emit("completed", err, value, "cache");
              return eventEmitter.removeAllListeners("completed");
            }
          }), input);
        });
        return process.nextTick(function() {
          return slow_fn.apply(this, [
            (function(err, value) {
              console.log("Llegue slow");
              eventEmitter.emit("completed", err, value, "slow_function");
              eventEmitter.removeAllListeners("completed");
              return cache_store(null, input, value);
            }), input
          ]);
        });
      };
    }
  };

  module.exports = memoize;

}).call(this);
