// Generated by CoffeeScript 1.6.3
(function() {
  var cache_retrieve, cache_store, data, memoize;

  data = {};

  cache_store = function(key, value, callback) {
    callback(null, value);
    return data[key] = value;
  };

  cache_retrieve = function(key, callback) {
    return callback(null, data[key]);
  };

  memoize = function(slow_fn) {
    var slice;
    if (typeof slow_fn === "function") {
      slice = Array.prototype.slice;
      return function() {
        var args, input, slow_fn_callback;
        args = slice.call(arguments);
        slow_fn_callback = args[1];
        input = args[0];
        return cache_retrieve(input, function(err, value) {
          if (value) {
            return slow_fn_callback(err, value);
          } else {
            return process.nextTick(function() {
              return slow_fn.apply(this, [
                input, function(err, value) {
                  return cache_store(input, value, function(err, value) {
                    return slow_fn_callback(err, value);
                  });
                }
              ]);
            });
          }
        });
      };
    }
  };

  module.exports = memoize;

}).call(this);
