// Generated by CoffeeScript 1.6.3
(function() {
  var cache_retrieve, cache_store, data, default_ttl, memoize;

  data = {};

  default_ttl = 7000;

  cache_store = function(callback, key, value) {
    if (callback) {
      callback(null, value);
    }
    return data[key] = value;
  };

  cache_retrieve = function(callback, key) {
    return callback(null, data[key]);
  };

  memoize = function(slow_fn, opts) {
    var slice;
    if (opts == null) {
      opts = {};
    }
    if (typeof slow_fn === "function") {
      slice = Array.prototype.slice;
      return function() {
        var args, input, slow_fn_callback, ttl;
        args = slice.call(arguments);
        slow_fn_callback = args[0];
        input = args[1];
        ttl = opts.ttl || default_ttl;
        return cache_retrieve((function(err, value) {
          if (value && value.ttl > Date.now()) {
            return slow_fn_callback(err, value.value);
          } else {
            return process.nextTick(function() {
              return slow_fn.apply(this, [
                (function(err, value) {
                  slow_fn_callback(err, value);
                  return cache_store(null, input, {
                    value: value,
                    ttl: Date.now() + ttl
                  });
                }), input
              ]);
            });
          }
        }), input);
      };
    }
  };

  module.exports = memoize;

}).call(this);
